### ISSUE TITLE
About using relative path

### ISSUE THREAD

**Issue by therimalaya** [jabranham/emacs#2]
Hello, 

I am new to Emacs. This is my 5th or 6th attempt to get into emacs. This time I am more closer than previous. I have used may codes from you emacs.org file. I want to ask a question about using relative path on `setq bibtex-completion-bibliography`. Is it possible that way.

**Comment by jabranham** [comment]
Relative to what? 

Emacs is going to evaluate that whenever it starts up, so it's not clear what it would be relative to. The way I do it now is to put my big bib file in Dropbox. Maybe describe what you're trying to do?

Glad it's helpful for you :+1:

**Comment by therimalaya** [comment]
Thank you for so quick reply,

Since, I compile a latex file which is in a folder. When I use `cite` command, can it populate the citation from the bib file in that folder or some bib file path relative to that folder?

**Comment by jabranham** [comment]
I'm not sure. This is the package I use: https://github.com/tmalsburg/helm-bibtex, you might look through their documentation and ask them. 

I do know that this is possible with Reftex, though.
